import type { CmsStandardPage } from "@/lib/cms-types";

// Temporary migration drafts. A published StandardPage with a non-empty body
// replaces the matching draft automatically.
const fallbackStandardPages: Record<string, CmsStandardPage> = {
  privacy: {
    id: -401,
    kind: "standard",
    title: "Privacy policy",
    meta: {
      type: "fallback.StandardPage",
      slug: "privacy",
      seoTitle: "Privacy policy — LaBio Media",
      searchDescription:
        "How LaBio Media handles information submitted through its website and client portal.",
    },
    socialImage: null,
    body: [
      {
        type: "rich_text",
        value:
          "<p><strong>Migration draft — 13 August 2026.</strong> This is starter website content intended to be reviewed and maintained through LaBio Media’s content management system. It describes the current website and client portal at a practical level and does not replace project-specific privacy information where that is required.</p>",
      },
      {
        type: "heading",
        value: { text: "Information that may be collected", level: "h2" },
      },
      {
        type: "rich_text",
        value:
          "<p>LaBio Media may receive information that you choose to provide or that is needed to operate the platform, including:</p><ul><li>your name, email address, organisation and project details submitted through the contact form;</li><li>client portal account information used to identify and authenticate you;</li><li>project messages, approval feedback and files shared through the portal;</li><li>information connected with enquiries, quotations and agreed project work; and</li><li>basic technical and security logs, such as IP address, browser information, request time and requested page, generated by hosting and application infrastructure.</li></ul>",
      },
      {
        type: "heading",
        value: { text: "Why information is used", level: "h2" },
      },
      {
        type: "rich_text",
        value:
          "<p>Information is used to respond to enquiries, prepare quotations, deliver agreed creative and media services, operate client accounts and project collaboration features, protect the security of the platform, troubleshoot technical problems, and meet reasonable administrative or legal record-keeping needs.</p>",
      },
      {
        type: "heading",
        value: { text: "Service providers", level: "h2" },
      },
      {
        type: "rich_text",
        value:
          "<p>LaBio Media uses specialist providers to operate the website and platform. These may include website hosting, application and database hosting, protected file storage and delivery, and email or other technical services. Information is shared with those providers only where needed to provide and secure the relevant service.</p>",
      },
      {
        type: "heading",
        value: { text: "Retention", level: "h2" },
      },
      {
        type: "rich_text",
        value:
          "<p>Information is kept only for as long as reasonably needed for the enquiry, project, client relationship, platform security, or applicable administrative and legal obligations. Retention periods can differ depending on the type of information and the project context.</p>",
      },
      {
        type: "heading",
        value: { text: "Your rights", level: "h2" },
      },
      {
        type: "rich_text",
        value:
          "<p>Under EU and Finnish data-protection law, you may have rights to request access to or correction of your personal data, and in some circumstances to request erasure, restriction, portability, or to object to processing. Where processing is based on consent, consent may be withdrawn. You may also contact the Finnish Data Protection Ombudsman if you have concerns about how personal data is handled.</p>",
      },
      {
        type: "heading",
        value: { text: "Privacy enquiries", level: "h2" },
      },
      {
        type: "rich_text",
        value:
          "<p>For a privacy question or request, use the <a href=\"/contact\">LaBio Media contact form</a> or the public contact address shown on this website. Please provide enough detail to identify the relevant enquiry, account or project.</p>",
      },
    ],
  },
  terms: {
    id: -402,
    kind: "standard",
    title: "Terms of service",
    meta: {
      type: "fallback.StandardPage",
      slug: "terms",
      seoTitle: "Terms of service — LaBio Media",
      searchDescription:
        "General terms for using the LaBio Media website and arranging project work.",
    },
    socialImage: null,
    body: [
      {
        type: "rich_text",
        value:
          "<p><strong>Migration draft — 13 August 2026.</strong> This starter text is intended to be reviewed and maintained through LaBio Media’s content management system. It provides general website and service information, not a substitute for an accepted quotation, project agreement or final legal review.</p>",
      },
      {
        type: "heading",
        value: { text: "Using this website", level: "h2" },
      },
      {
        type: "rich_text",
        value:
          "<p>You may use this website to learn about LaBio Media, view public work, and make genuine enquiries. Do not misuse the site, interfere with its security or availability, attempt unauthorised access, or use its content in a way that infringes another person’s rights.</p>",
      },
      {
        type: "heading",
        value: { text: "Enquiries, quotations and project scope", level: "h2" },
      },
      {
        type: "rich_text",
        value:
          "<p>A website enquiry does not by itself create a project agreement. Scope, deliverables, timing, price and any project-specific conditions are confirmed separately in a quotation, proposal or other written agreement. Material changes to an agreed scope may require a revised schedule or quotation.</p>",
      },
      {
        type: "heading",
        value: { text: "Client responsibilities", level: "h2" },
      },
      {
        type: "rich_text",
        value:
          "<p>Clients are responsible for providing accurate briefs, materials, access and feedback reasonably needed for the work. Clients should ensure they have permission to supply and authorise the use of text, images, data, trademarks and other materials provided for a project.</p>",
      },
      {
        type: "heading",
        value: { text: "Intellectual property and usage rights", level: "h2" },
      },
      {
        type: "rich_text",
        value:
          "<p>Ownership, licences, credits and permitted uses for commissioned work are defined in the relevant quotation or project agreement. Rights in third-party materials, software, fonts, stock assets and platforms remain subject to their respective licences and terms.</p>",
      },
      {
        type: "heading",
        value: { text: "Project files and delivery", level: "h2" },
      },
      {
        type: "rich_text",
        value:
          "<p>Drafts, previews, approvals and final deliveries may be shared through the client portal or another agreed method. File formats, included source materials and delivery arrangements depend on the agreed project scope. Clients should keep their own copies of final delivered files.</p>",
      },
      {
        type: "heading",
        value: { text: "Third-party services", level: "h2" },
      },
      {
        type: "rich_text",
        value:
          "<p>Projects and the platform may rely on third-party hosting, storage, software, production or delivery services. Those services may have their own terms, licences and availability conditions. LaBio Media will use reasonable care when selecting and working with them.</p>",
      },
      {
        type: "heading",
        value: { text: "Prices and payment", level: "h2" },
      },
      {
        type: "rich_text",
        value:
          "<p>Any public price examples are starting points only. The final price and payment arrangements for a project are stated in its quotation, agreement or invoice. No additional payment deadline or cancellation rule is created by this general page.</p>",
      },
      {
        type: "heading",
        value: { text: "Availability and responsibility", level: "h2" },
      },
      {
        type: "rich_text",
        value:
          "<p>Reasonable care is taken to keep public information and platform services useful and available, but uninterrupted or error-free operation cannot be guaranteed. Project-specific responsibilities are governed by the relevant agreement, and nothing on this page limits rights or responsibilities that cannot lawfully be limited.</p>",
      },
      {
        type: "heading",
        value: { text: "Changes and contact", level: "h2" },
      },
      {
        type: "rich_text",
        value:
          "<p>These general terms may be updated as the website and services evolve. Changes do not replace separately agreed project terms. Questions can be sent through the <a href=\"/contact\">LaBio Media contact form</a> or the public contact address shown on this website.</p>",
      },
    ],
  },
};

export function findFallbackStandardPage(slug: string): CmsStandardPage | null {
  return fallbackStandardPages[slug] ?? null;
}
